### ISSUE TITLE
Need to use `__xonsh__.completers` instead of deprecated `__xonsh_completers__`

### ISSUE THREAD

**Issue by Achimh3011** [Granitas/xonsh-vox-tabcomplete#4]
How to reproduce: start xonsh >0.8 with vox_tabcomplete.xsh activated and this warning appears:

````
/usr/local/Cellar/xonsh/0.8.3/libexec/lib/python3.7/site-packages/xontrib/vox_tabcomplete.xsh:30: DeprecationWarning: __xonsh_completers__ has been deprecated, please use __xonsh__.completers instead.
  __xonsh_completers__['vox'] = _vox_completer
`````

**Comment by airdrik** [comment]
Somewhere along the line (as of xonsh 0.9.27; though I think it happened somewhere since 0.9.24 since iirc it was working before there), that __xonsh_completers__ reference has been removed and vox_tabcomplete now completely fails to load.
