### ISSUE TITLE
Add tags to repo

### ISSUE THREAD

**Issue by anki-code** [Granitas/xonsh-vox-tabcomplete#7]
Hi! Thank you for the useful xontrib!

Please add `xonsh` and `xontrib` tags to the repo:

![image](https://user-images.githubusercontent.com/1708680/94840154-a940e880-0420-11eb-8d2d-d99bd2d71959.png)

It helps [spread the word about xontrib on Github](https://github.com/topics/xontrib).

Thanks!

**Comment by anki-code** [comment]
Hi @Granitosaurus! Please take a look

**Comment by Granitosaurus** [comment]
added!

**Comment by anki-code** [comment]
Hi @Granitosaurus ! Thanks! Could you place replace `crontrib` tag to `xontrib`?

**Comment by Granitosaurus** [comment]
> Hi @Granitosaurus ! Thanks! Could you place replace `crontrib` tag to `xontrib`?

done!
